import {customerAuthRoutes,orderAccess} from '@/lib/customer-auth';
import {db,getProducts,getSettings,publicConfig,runtime,session,requireMutation,body,rateLimit,requireAdmin,audit,json,boundedRequest} from '@/lib/server';
import {getCart,setCart,checkout,reconcile,orderView,type Order} from '@/lib/commerce';
import {assert,string,email,int,HttpError} from '@/lib/security';
import {verifyWebhook} from '@/lib/iyzico';
import {defaultSettings} from '@/lib/catalog';
import {refundOrder} from '@/lib/refund';
import {adminExtensions,adminReadOrders,publicMedia} from '@/lib/admin-extensions';
import {drainMail,mailStatus} from '@/lib/mail';
import {mailConfig} from '@/lib/mail-config';
import {adminAuthRoutes} from '@/lib/admin-auth';
export const dynamic='force-dynamic';
async function handle(req:Request){const url=new URL(req.url),path=url.pathname.slice(5);try{
if(req.method==='POST')req=await boundedRequest(req,path==='admin/media/upload'?4*1024*1024:path==='admin/products/save'?64000:16000);
if(path.startsWith('media/')&&req.method==='GET')return publicMedia(path);
if(path==='products'&&req.method==='GET')return json({products:(await getProducts()).filter(p=>p.active),config:await publicConfig()});
if(path==='payments/callback'&&req.method==='POST'){await rateLimit(req,'callback',30);assert(Number(req.headers.get('content-length')||0)<5000,413,'İstek çok büyük.');const text=await req.text();assert(text.length<5000,413,'İstek çok büyük.');const token=string(new URLSearchParams(text).get('token'),10,500);const order=await db().prepare('SELECT * FROM orders WHERE token=?').bind(token).first<Order>();assert(order,404,'Ödeme bulunamadı.');let status='bekliyor';try{await reconcile(order);status='kontrol-edildi';}catch{/* The public redirect carries no payment authority. Reconciliation remains repeatable. */}return Response.redirect(String(runtime().APP_ORIGIN)+'/siparisler?odeme='+status,303);}
if(path==='payments/webhook'&&req.method==='POST'){const payload=await body(req);await verifyWebhook(req,payload);assert(payload.iyziEventType==='CHECKOUT_FORM_AUTH',400,'Bildirim türü desteklenmiyor.');const token=string(payload.token,10,500);const order=await db().prepare('SELECT * FROM orders WHERE token=?').bind(token).first<Order>();assert(order&&payload.paymentConversationId===order.id,404,'Ödeme kaydı bulunamadı.');await reconcile(order);return json({received:true});}
await rateLimit(req,path.startsWith('admin')?'admin':'public',path.startsWith('admin')?150:100);
const s=await session(req,req.method==='GET');if(req.method!=='GET')await requireMutation(req,s);
const customerResponse=await customerAuthRoutes(req,path,s);if(customerResponse)return customerResponse;
if(path==='cart'&&req.method==='GET')return json(await getCart(s),200,s.cookie);
if(path==='cart'&&req.method==='POST')return json(await setCart(s,await body(req)));
if(path==='checkout'&&req.method==='POST'){await rateLimit(req,'checkout',6);return json(await checkout(req,s,await body(req)));}
if(path==='requests'&&req.method==='POST'){await rateLimit(req,'requests',8);const data=await body(req);assert(!data.website,400,'İstek kaydedilemedi.');const kind=string(data.kind,1,20);assert(['stock','contact','return'].includes(kind),400,'Geçersiz talep.');const mail=email(data.email),productId=kind==='stock'?string(data.productId,1,30):null,message=string(data.message??'',kind==='stock'?0:10,2500);if(productId)assert((await getProducts()).some(p=>p.id===productId),404,'Ürün bulunamadı.');const recent=await db().prepare('SELECT id FROM requests WHERE kind=? AND email=? AND COALESCE(product_id,\'\')=? AND created_at>?').bind(kind,mail,productId||'',Date.now()-86400000).first();if(!recent){const id=crypto.randomUUID(),now=Date.now();await db().batch([db().prepare('INSERT INTO requests(id,kind,email,product_id,body,status,created_at) VALUES(?,?,?,?,?,?,?)').bind(id,kind,mail,productId,JSON.stringify({message,name:string(data.name??'',0,100),orderNumber:string(data.orderNumber??'',0,40),consent:kind==='stock'?'single_stock_notification':'requested_contact'}),'new',now),db().prepare('INSERT INTO notification_outbox(id,source_id,kind,updated_at) VALUES(?,?,?,?)').bind('receipt:'+id,id,'request_received',now)]);}await drainMail();return json({ok:true,message:kind==='stock'?'Talebin kaydedildi. Ürün hazır olduğunda bu adres üzerinden iletişime geçeceğiz.':'Mesajın bize ulaştı. Talebini inceleyip seninle iletişime geçeceğiz.'});}
if(path==='orders'&&req.method==='GET'){const access=await orderAccess(req,s);const rows=await db().prepare('SELECT * FROM orders WHERE '+access.condition+' ORDER BY created_at DESC LIMIT 30').bind(...access.values).all<Order>();return json({orders:await Promise.all(rows.results.map(orderView))},200,s.cookie);}
if(path==='orders/reconcile'&&req.method==='POST'){const data=await body(req);const access=await orderAccess(req,s);const order=await db().prepare('SELECT * FROM orders WHERE number=? AND '+access.condition).bind(string(data.number,10,40),...access.values).first<Order>();assert(order,404,'Sipariş bulunamadı.');await reconcile(order);return json({ok:true});}
if(path==='orders/resume'&&req.method==='POST'){const data=await body(req);const access=await orderAccess(req,s);const order=await db().prepare('SELECT * FROM orders WHERE number=? AND '+access.condition).bind(string(data.number,10,40),...access.values).first<Order>();assert(order&&order.status==='pending'&&order.payment_url&&Number(order.expires)>Date.now(),409,'Bu ödeme bağlantısı artık kullanılamıyor. Önce ödeme durumunu kontrol et.');return json({url:order.payment_url});}
if(path==='orders/lookup'&&req.method==='POST'){await rateLimit(req,'lookup',8);const data=await body(req),number=string(data.number,10,40),mail=email(data.email);const order=await db().prepare('SELECT * FROM orders WHERE number=? AND customer_id IS NULL').bind(number).first<Order>();assert(order&&JSON.parse(order.customer).email===mail,404,'Bu bilgilerle eşleşen sipariş bulunamadı.');const view=await orderView(order);return json({number:view.number,status:view.status,total:view.total,createdAt:view.createdAt,tracking:view.tracking,carrier:view.carrier,items:view.items});}
const authResponse=await adminAuthRoutes(req,path,s);if(authResponse)return authResponse;
if(path.startsWith('admin')){const actor=await requireAdmin(req);const extension=await adminExtensions(req,path,actor);if(extension)return extension;
if(path==='admin'&&req.method==='GET'){const [products,settings,orders,requests,logs]=await Promise.all([getProducts(),getSettings(),adminReadOrders(url),db().prepare('SELECT * FROM requests ORDER BY created_at DESC LIMIT 100').all(),db().prepare('SELECT action,target,created_at FROM audit_log ORDER BY created_at DESC LIMIT 40').all()]);return json({products,settings,orders:await Promise.all(orders.results.map(o=>orderView(o as Order))),pagination:orders.pagination,requests:requests.results,audit:logs.results,config:await publicConfig(),admin:actor,notifications:await mailStatus(),readiness:{apiKeys:!!(runtime().IYZICO_API_KEY&&runtime().IYZICO_SECRET_KEY),live:runtime().IYZICO_MODE==='live',paymentVerified:runtime().IYZICO_VERIFIED==='true',email:mailConfig().configured&&!mailConfig().testMode,privateBootstrap:runtime().ADMIN_BOOTSTRAP_PRIVATE==='true'}},200,s.cookie);}
if(path==='admin/product'&&req.method==='POST'){const data=await body(req);const id=string(data.id,1,30),price=int(data.priceCents,100,100000000),delta=int(data.inventoryDelta, -100000,100000),active=data.active===true;const p=(await getProducts()).find(p=>p.id===id);assert(p,404,'Ürün bulunamadı.');const name=string(data.name,2,180),subtitle=string(data.subtitle,10,1000);const updated=await db().prepare('UPDATE products SET data=?,price=?,stock=stock+?,active=?,updated_at=? WHERE id=? AND stock+? BETWEEN 0 AND 100000 RETURNING id').bind(JSON.stringify({...p,name,subtitle}),price,delta,active?1:0,Date.now(),id,delta).first();assert(updated,409,'Stok değişti. Negatif stok oluşturulamaz.');await audit(actor,'product.update',id+'; inventoryDelta='+delta);return json({ok:true});}
if(path==='admin/settings'&&req.method==='POST'){const data=await body(req);const b:Record<string,string>={};assert(data.business&&typeof data.business==='object',400,'İşletme bilgileri gerekli.');for(const key of Object.keys(defaultSettings.business))b[key]=string(data.business[key]??'',0,key.toLowerCase().includes('address')?500:200);if(b.email)email(b.email);const settings={checkoutEnabled:data.checkoutEnabled===true,shippingConfigured:data.shippingConfigured===true,shippingCents:int(data.shippingCents,0,100000),freeShippingCents:int(data.freeShippingCents,0,100000000),dispatchDays:int(data.dispatchDays,1,30),legalReviewed:data.legalReviewed===true,business:b};await db().prepare("INSERT INTO settings(key,value) VALUES('store',?) ON CONFLICT(key) DO UPDATE SET value=json_patch(settings.value,excluded.value)").bind(JSON.stringify(settings)).run();await audit(actor,'settings.update','store');return json({ok:true});}
if(path==='admin/order'&&req.method==='POST'){const data=await body(req);const order=await db().prepare('SELECT * FROM orders WHERE number=?').bind(string(data.number,10,40)).first<Order>();assert(order,404,'Sipariş bulunamadı.');if(data.action==='reconcile'){await reconcile(order);}else if(data.action==='refund'){assert(data.confirmation===order.number,400,'Sipariş onayı eşleşmedi.');await refundOrder(order);}else if(data.action==='resolve_unpaid'){assert(['initializing','pending','review','reconcile','rejected'].includes(order.status),409,'Bu sipariş bu işlemle kapatılamaz.');assert(data.confirmation===order.number,400,'Sipariş onayı eşleşmedi.');const evidence=string(data.evidence,15,300);assert(Date.now()-order.created_at>3600000,409,'Yeni bir ödeme henüz belirsiz olabilir. Sağlayıcı sonucunu bekle.');await db().prepare("UPDATE orders SET status='failed',updated_at=? WHERE id=? AND status IN ('initializing','pending','review','reconcile','rejected')").bind(Date.now(),order.id).run();await audit(actor,'order.unpaid_evidence',order.number+': '+evidence);}else if(data.action==='ship'){assert(order.status==='paid',409,'Yalnızca ödemesi onaylanan sipariş gönderilebilir.');await db().prepare("UPDATE orders SET status='shipped',tracking=?,carrier=?,updated_at=? WHERE id=? AND status='paid'").bind(string(data.tracking,3,100),string(data.carrier,2,80),Date.now(),order.id).run();}else if(data.action==='deliver'){assert(order.status==='shipped',409,'Sipariş henüz kargoya verilmedi.');await db().prepare("UPDATE orders SET status='delivered',updated_at=? WHERE id=? AND status='shipped'").bind(Date.now(),order.id).run();}else throw new HttpError(400,'Geçersiz işlem.');await drainMail(order.id);await audit(actor,'order.'+data.action,order.number);return json({ok:true});}
if(path==='admin/request'&&req.method==='POST'){const data=await body(req);const id=string(data.id,10,50);await db().prepare("UPDATE requests SET status='resolved' WHERE id=?").bind(id).run();await audit(actor,'request.resolve',id);return json({ok:true});}
if(path==='admin/notifications/test'&&req.method==='POST'){await rateLimit(req,'notification-test',3);assert(mailConfig().configured&&runtime().STORE_NOTIFICATION_EMAIL,503,'E-posta bağlantısı henüz hazır değil.');const id='test:'+crypto.randomUUID();await db().prepare('INSERT INTO notification_outbox(id,source_id,kind,updated_at) VALUES(?,?,?,?)').bind(id,id,'test',Date.now()).run();await drainMail(id);const result=await db().prepare('SELECT status FROM notification_outbox WHERE id=?').bind(id).first<{status:string}>();await audit(actor,'notifications.test',id);assert(result?.status==='sent',502,'Test mesajı kaydedildi ancak sağlayıcı kabulü doğrulanamadı. Gönderim durumunu kontrol et.');return json({ok:true,notifications:await mailStatus()});}
if(path==='admin/notifications/retry'&&req.method==='POST'){const result=await drainMail();await audit(actor,'notifications.retry','outbox');return json({...result,notifications:await mailStatus()});}
if(path==='admin/maintenance'&&req.method==='POST'){const stale=await db().prepare("SELECT * FROM orders WHERE status IN ('pending','review','reconcile') AND token IS NOT NULL AND updated_at<? LIMIT 5").bind(Date.now()-3600000).all<Order>();for(const order of stale.results){try{await reconcile(order)}catch{/* Unknown results retain inventory for an audited operator decision. */}}await db().batch([db().prepare('DELETE FROM rate_limits WHERE expires<?').bind(Date.now()),db().prepare('DELETE FROM cart_items WHERE session IN (SELECT id FROM sessions WHERE expires<?)').bind(Date.now()),db().prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()),db().prepare('DELETE FROM customer_sessions WHERE expires<=? OR last_seen<=?').bind(Date.now(),Date.now()-7*86400000),db().prepare('DELETE FROM customer_reset_tokens WHERE expires<=?').bind(Date.now())]);await drainMail();await audit(actor,'maintenance.run','expired_sessions');return json({ok:true});}
}
throw new HttpError(404,'Aradığın sayfa bulunamadı.');
}catch(error){if(error instanceof HttpError)return json({error:error.message},error.status);console.error('Store operation failed',{path,errorType:error instanceof Error?error.name:'unknown'});return json({error:'İşlem tamamlanamadı. Lütfen biraz sonra tekrar dene.'},500);}}
export const GET=handle;export const POST=handle;
