'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {LockKeyhole,Eye,EyeOff,ArrowRight,ArrowUpRight,ShieldCheck,Monitor,LogOut,KeyRound,LoaderCircle} from 'lucide-react';
import {useShop} from './shop-context';
import {useLanguage} from './localization';
import {LanguageSwitch} from './storefront-enhancements';
import {toast} from '@/lib/notifications';

export function AdminLogin({onSuccess,notice}:{onSuccess:()=>Promise<void>;notice?:string}){
  const {request}=useShop(),{t}=useLanguage();
  const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[show,setShow]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  return <main id="main-content" className="admin-access-page">
    <aside className="admin-access-brand"><Link href="/" className="wordmark">sistercraft&co.</Link><div><span className="eyebrow">{t('SENİN MAĞAZAN. SENİN KONTROLÜN.','YOUR STORE. YOUR CONTROL.')}</span><h1>{t('Her küçük detay,','Every little detail,')}<br/>{t('tek bir yerde.','in one place.')}</h1><p>{t('Ürünlerini, siparişlerini ve mağazanın ritmini yönet.','Manage your products, orders and the rhythm of your store.')}</p></div><span className="access-brand-footer">SISTERCRAFT&CO · {t('YÖNETİM','ADMINISTRATION')}</span></aside>
    <section className="admin-access-form"><div className="access-top"><Link href="/">{t('Mağazaya dön','Back to store')}<ArrowUpRight size={16}/></Link><LanguageSwitch/></div><div className="access-form-inner"><span className="access-lock"><LockKeyhole size={26}/></span><span className="eyebrow">{t('YETKİLİ ERİŞİM','AUTHORISED ACCESS')}</span><h2>{t('Mağazana hoş geldin.','Welcome to your store.')}</h2><p>{t('Devam etmek için yönetici bilgilerinle giriş yap.','Sign in with your administrator credentials to continue.')}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await request('admin/auth/login',{username,password});setPassword('');await onSuccess()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}} className="form-stack">
      <label>{t('Kullanıcı adı','Username')}<input autoComplete="username" name="username" autoCapitalize="none" spellCheck={false} required minLength={3} maxLength={40} value={username} onChange={e=>setUsername(e.target.value)} autoFocus/></label>
      <label>{t('Şifre','Password')}<span className="access-password"><input name="password" type={show?'text':'password'} autoComplete="current-password" required maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setShow(v=>!v)} aria-label={t(show?'Şifreyi gizle':'Şifreyi göster',show?'Hide password':'Show password')}>{show?<EyeOff size={19}/>:<Eye size={19}/>}</button></span></label>
      {error&&<p role="alert" className="error-text">{t(error)}</p>}
      <button className="button full-width" disabled={busy}>{busy?<LoaderCircle size={18} className="loading-spinner"/>:<>{t('Giriş yap','Sign in')}<ArrowRight size={18}/></>}</button>
    </form><div className="access-security-note"><ShieldCheck size={17}/><span>{t('30 dakika işlem yapılmadığında oturum otomatik kapanır.','Your session expires after 30 minutes of inactivity.')}</span></div>{notice&&!notice.includes('giriş yap')&&<p className="access-notice">{t(notice)}</p>}</div><small className="access-copyright">© {new Date().getFullYear()} SisterCraft&Co</small></section>
  </main>;
}

export function AdminSecurity({onSignedOut}:{onSignedOut:()=>void}){
  const {request}=useShop(),{t,locale}=useLanguage();
  const [info,setInfo]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[current,setCurrent]=useState(''),[next,setNext]=useState(''),[confirmation,setConfirmation]=useState('');
  const load=()=>request('admin/auth/sessions').then(setInfo).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[request]);
  const date=(value:number)=>new Date(value).toLocaleString(locale==='en'?'en-GB':'tr-TR',{dateStyle:'medium',timeStyle:'short'});
  return <div className="admin-access-security"><div className="access-security-grid"><section className="panel-card"><div className="panel-heading"><div><span className="security-heading-icon"><KeyRound size={20}/></span><h2>{t('Giriş ve şifre','Login & password')}</h2></div><span className="visibility-tag">{t('Şifre korumalı','Password protected')}</span></div><p className="admin-explainer">{t('Şifre değiştiğinde bu cihaz dahil tüm yönetim oturumları kapatılır.','Changing the password signs out every admin session, including this device.')}</p><form className="form-stack" onSubmit={async e=>{e.preventDefault();setError('');if(next!==confirmation){setError(t('Yeni şifreler eşleşmiyor.','New passwords do not match.'));return}setBusy(true);try{await request('admin/auth/password',{currentPassword:current,newPassword:next});setCurrent('');setNext('');setConfirmation('');toast.success(t('Şifren değişti. Yeni şifrenle giriş yap.','Password changed. Sign in with your new password.'));onSignedOut()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>
      <label>{t('Kullanıcı adı','Username')}<input value={info?.username||''} readOnly autoComplete="username"/></label>
      <label>{t('Mevcut şifre','Current password')}<input type="password" autoComplete="current-password" required maxLength={128} value={current} onChange={e=>setCurrent(e.target.value)}/></label>
      <label>{t('Yeni şifre · en az 16 karakter','New password · at least 16 characters')}<input type="password" autoComplete="new-password" required minLength={16} maxLength={128} value={next} onChange={e=>setNext(e.target.value)}/></label>
      <label>{t('Yeni şifreyi tekrar yaz','Repeat new password')}<input type="password" autoComplete="new-password" required minLength={16} maxLength={128} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label>
      {error&&<p className="error-text" role="alert">{t(error)}</p>}<button className="button" disabled={busy}><KeyRound size={17}/>{t('Şifreyi güncelle','Update password')}</button>
    </form></section><section className="panel-card"><div className="panel-heading"><h2>{t('Aktif oturumlar','Active sessions')}</h2><ShieldCheck size={21}/></div><p className="admin-explainer">{t('Tanımadığın bir cihaz varsa oturumunu kapat. En uzun oturum süresi 8 saattir.','Sign out any device you do not recognise. Sessions last no longer than eight hours.')}</p><div className="admin-session-list">{info?.sessions.map((s:any)=><div key={s.id}><Monitor size={21}/><div><strong>{s.current?t('Bu cihaz','This device'):t('Diğer cihaz','Another device')}</strong><small title={s.device}>{s.device.includes('Windows')?'Windows':s.device.includes('iPhone')?'iPhone':s.device.includes('Android')?'Android':s.device.includes('Mac')?'Mac':t('Web tarayıcısı','Web browser')}</small><small>{t('Son etkinlik: ','Last activity: ')}{date(s.lastSeenAt)}</small></div>{s.current?<span className="visibility-tag">{t('Şu an','Current')}</span>:<button type="button" className="icon-button" disabled={busy} aria-label={t('Oturumu kapat','Revoke session')} onClick={async()=>{setBusy(true);try{await request('admin/auth/revoke',{id:s.id});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><LogOut size={17}/></button>}</div>)}</div><button className="button secondary" disabled={busy||!info?.sessions.some((s:any)=>!s.current)} onClick={async()=>{setBusy(true);try{await request('admin/auth/revoke',{others:true});await load();toast.success(t('Diğer oturumlar kapatıldı.','Other sessions signed out.'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><LogOut size={16}/>{t('Diğer tüm oturumları kapat','Sign out all other sessions')}</button></section></div></div>;
}
