'use client';
import {createContext,useContext,useState,useEffect,useMemo,Children,isValidElement,cloneElement,type ReactNode,type ReactElement} from 'react';
import translations from '@/lib/ui-en.json';
import englishProducts from '@/lib/catalog-en.json';
import {initialProducts,type Product,type PublicConfig,money} from '@/lib/catalog';
export type Locale='tr'|'en';
type LanguageState={locale:Locale;setLocale:(l:Locale)=>void;t:(s:string,en?:string)=>string;format:(cents:number)=>string;localizeProduct:(p:Product)=>Product;config:PublicConfig};
const LanguageContext=createContext<LanguageState|null>(null);
export function useLanguage(){const c=useContext(LanguageContext);if(!c)throw Error('Language provider missing');return c;}
const productCopy=englishProducts as Record<string,Partial<Product>>;
const dictionary:Record<string,string>={...translations};
for(const p of initialProducts){const en=productCopy[p.id];if(en){dictionary[p.name]=en.name||p.name;dictionary[p.subtitle]=en.subtitle||p.subtitle;}}
Object.assign(dictionary,{'Tüm koleksiyon':'All products','Tütsüler':'Incense','Mumlar':'Candles','Ritüel kutuları':'Ritual boxes','Ekilebilir hediyeler':'Plantable gifts','Kargo':'Shipping','Ad':'First name','Soyad':'Last name','İl':'City','İlçe':'District','E-posta':'Email','Adet':'Quantity','Sepet':'Bag','Türkiye · Türkçe · TRY ₺':'Türkiye · English · USD $','Sepete ekle':'Add to bag','Sepetime ekle':'Add to bag','Stok bekleniyor':'Awaiting stock','Sepette':'In your bag','Türkçe':'Türkçe','Görünür':'Visible','Gizli':'Hidden'});
export function translateText(text:string,locale:Locale){if(locale==='tr')return text;const trimmed=text.trim(),normalized=trimmed.replace(/\s+/g,' ');const value=dictionary[trimmed]??dictionary[normalized];if(value)return text.replace(trimmed,value);return text.replace(/^(\d+) ürün$/,'$1 products').replace(/^(\d+) adet$/,'$1 items').replace(/^Fotoğraf (\d+)$/,'Photo $1');}
export function LanguageProvider({children,initialLocale,config}:{children:ReactNode;initialLocale:Locale;config:PublicConfig}){const[locale,setLocaleState]=useState(initialLocale);const setLocale=(next:Locale)=>{setLocaleState(next);document.cookie=`sc_language=${next}; Path=/; SameSite=Lax; Max-Age=31536000${location.protocol==='https:'?'; Secure':''}`;document.documentElement.lang=next;};useEffect(()=>{document.documentElement.lang=locale},[locale]);const value=useMemo<LanguageState>(()=>({locale,setLocale,t:(s,en)=>locale==='en'?(en??translateText(s,locale)):s,format:cents=>locale==='en'?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Math.round(cents/config.exchange.tryPerUsd)/100):money(cents),localizeProduct:p=>locale==='en'?{...p,...(p.en||productCopy[p.id]||{})}:p,config}),[locale,config]);return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>}
/** Localize React text/accessible labels without editing the DOM or form values. */
export function Localized({children,nativeCurrency=false}:{children:ReactNode;nativeCurrency?:boolean}){const{locale,format}=useLanguage();function walk(node:ReactNode,native:boolean):ReactNode{return Children.map(node,(child)=>{if(typeof child==='string'){if(!native&&locale==='en'&&/^₺[\d.,]+$/.test(child.trim()))return format(Math.round(Number(child.trim().slice(1).replaceAll('.','').replace(',','.'))*100));return translateText(child,locale);}if(!isValidElement(child))return child;const element=child as ReactElement<Record<string,any>>,props=element.props;const keep=native||!!props['data-native-currency'];const translated:Record<string,unknown>={};for(const name of ['aria-label','title','placeholder','alt'])if(typeof props[name]==='string')translated[name]=translateText(props[name],locale);if(props.children!==undefined)translated.children=walk(props.children,keep);return cloneElement(element,translated);});}return <>{walk(children,nativeCurrency)}</>}
export function CurrencyNote({total}:{total?:number}){const{locale,config}=useLanguage();if(locale!=='en')return null;return <p className="currency-note" data-native-currency>USD prices are estimates using the TCMB rate of {config.exchange.rateDate}: 1 USD = {config.exchange.tryPerUsd.toFixed(4)} TRY. {total!==undefined&&<>Amount charged: <strong>{money(total)} TRY.</strong> </>}Payment is charged in TRY. Your bank determines its conversion rate.</p>}
