'use client';
import {useState} from 'react';
import {ShieldCheck,LoaderCircle} from 'lucide-react';
import {useShop} from './shop-context';
import {useLanguage} from './localization';

type State={apiKeys:boolean;live:boolean;paymentVerified:boolean;email:boolean;privateBootstrap:boolean};
export function PaymentReadiness({readiness,business}:{readiness:State;business:Record<string,string>}){
  const{request}=useShop(),{t}=useLanguage();const[busy,setBusy]=useState(false),[result,setResult]=useState(''),[error,setError]=useState('');
  const labels:Record<string,string>={name:'Resmî satıcı unvanı',address:'İşletme adresi',taxOffice:'Vergi dairesi',taxNumber:'Vergi numarası',kep:'KEP adresi',email:'Destek e-postası',phone:'Telefon',returnAddress:'İade adresi',returnCarrier:'İade taşıyıcısı'};
  const missing=Object.keys(labels).filter(key=>!business[key]?.trim());
  return <section className="panel-card payment-readiness"><h2><ShieldCheck size={20}/>{t('Ödeme bağlantısı ve satış hazırlığı','Payment connection and launch readiness')}</h2><p>{t('Anahtarlar yalnızca Vercel sunucu ayarlarından okunur. Bağlantı kontrolü kart bilgisi istemez ve ödeme oluşturmaz.','Credentials are read only from server settings. The connection check needs no card details and creates no payment.')}</p><ul><li>{t('API anahtarları','API credentials')}: {readiness.apiKeys?t('Kayıtlı','Configured'):t('Eksik','Missing')}</li><li>{t('Ödeme ortamı','Payment environment')}: {readiness.live?'Live':'Sandbox / eksik'}</li><li>{t('Ödeme akışları doğrulandı','Payment flows verified')}: {readiness.paymentVerified?t('Evet','Yes'):t('Henüz tamamlanmadı','Not completed')}</li><li>{t('Tüm müşterilere e-posta gönderimi','Email delivery to all customers')}: {readiness.email?t('Hazır','Ready'):t('Test modunda veya eksik','Test mode or incomplete')}</li></ul>{missing.length>0&&<p className="error-text">{t('Eksik işletme alanları','Missing business details')}: {missing.map(k=>labels[k]).join(', ')}</p>}<button className="button" disabled={busy||!readiness.apiKeys} onClick={async()=>{setBusy(true);setResult('');setError('');try{const response=await request('admin/payment/check',{});setResult(t('iyzico '+response.mode+' bağlantısı doğrulandı. Ödeme alınmadı. Bu kontrol, başarılı/başarısız ödeme ve iade testlerinin yerine geçmez.','iyzico '+response.mode+' connection verified. No charge was created. Payment and refund tests are still required.'))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?<LoaderCircle size={17} className="loading-spinner"/>:<ShieldCheck size={17}/>} {t('iyzico bağlantısını kontrol et','Check iyzico connection')}</button>{result&&<output className="payment-check-result">{result}</output>}{error&&<p className="error-text" role="alert">{error}</p>}</section>;
}
