import {env} from '@store/runtime';
import {db,getProducts,getSettings,audit,json,body} from './server';
import {assert,string,int} from './security';
import {categories,initialProducts,type Product} from './catalog';
import {fetchOfficialRate} from './exchange';

const paidStates="'paid','shipped','delivered','refund_pending','refunded'";
const salesCte="WITH sales AS (SELECT o.*,MIN(o.total,CASE WHEN o.status='refunded' THEN o.total ELSE COALESCE(r.refunded,0) END) AS refunded_amount FROM orders o LEFT JOIN (SELECT order_id,SUM(amount) AS refunded FROM refund_actions WHERE status='confirmed' GROUP BY order_id) r ON r.order_id=o.id) ";
export async function adminReadOrders(url:URL){const q=(url.searchParams.get('q')||'').slice(0,100),status=url.searchParams.get('status')||'',page=int(Number(url.searchParams.get('page')||1),1,10000);const valid=['initializing','pending','review','reconcile','paid','shipped','delivered','failed','rejected','refund_pending','refunded'];assert(!status||valid.includes(status),400,'Geçersiz sipariş durumu.');const condition="WHERE (?='' OR status=?) AND (?='' OR number LIKE ? OR json_extract(customer,'$.email') LIKE ? OR json_extract(customer,'$.name') LIKE ? OR json_extract(customer,'$.surname') LIKE ?)";const values=[status,status,q,...Array(4).fill('%'+q+'%')];const[count,rows]=await Promise.all([db().prepare('SELECT COUNT(*) AS n FROM orders '+condition).bind(...values).first<{n:number}>(),db().prepare('SELECT * FROM orders '+condition+' ORDER BY created_at DESC LIMIT 30 OFFSET ?').bind(...values,(page-1)*30).all()]);return{...rows,pagination:{page,total:count?.n||0,pages:Math.max(1,Math.ceil((count?.n||0)/30))}};}
function lines(value:unknown,max=30){assert(Array.isArray(value)&&value.length<=max,400,'Liste bilgisi geçersiz.');return value.map(v=>string(v,1,1500));}
function features(value:unknown){assert(value&&typeof value==='object'&&!Array.isArray(value),400,'Ürün özelliklerini kontrol et.');const entries=Object.entries(value);assert(entries.length<=25,400,'En fazla 25 özellik eklenebilir.');return Object.fromEntries(entries.map(([k,v])=>[string(k,1,100),string(v,1,500)]));}
async function safeImages(value:unknown){const values=lines(value,12);assert(values.length>0,400,'En az bir ürün fotoğrafı gerekli.');for(const v of values)assert(/^\/(products\/[a-zA-Z0-9_-]+\.(jpg|png|webp)|api\/media\/[a-f0-9-]+\.(jpg|png|webp))$/.test(v),400,'Medya kütüphanesinden bir görsel seç.');const known=new Set(initialProducts.flatMap(p=>p.images));await Promise.all(values.map(async v=>{assert(known.has(v)||(v.startsWith('/api/media/')&&env.MEDIA&&await env.MEDIA.head('products/'+v.slice('/api/media/'.length))),400,'Görsel medya kütüphanesinde bulunamadı.');}));return [...new Set(values)];}
async function saveProduct(data:Record<string,unknown>,actor:string){const list=await getProducts(),existing=data.id?list.find(p=>p.id===data.id):undefined;assert(!data.id||existing,404,'Ürün bulunamadı.');const group=string(data.group,1,30);assert(categories.some(c=>c.id===group&&group!=='tumu'),400,'Geçerli bir kategori seç.');const price=int(data.priceCents,100,100000000),delta=int(data.inventoryDelta,-100000,100000);assert(existing||delta>=0,400,'Yeni ürün negatif stokla başlayamaz.');const enInput=data.en as Record<string,unknown>;assert(enInput&&typeof enInput==='object',400,'İngilizce ürün bilgileri gerekli.');const id=existing?.id||'sc_'+crypto.randomUUID().replaceAll('-','').slice(0,18);const p:Product={...(existing||{}),id,name:string(data.name,2,180),subtitle:string(data.subtitle,10,1000),description:string(data.description,20,6000),details:lines(data.details),features:features(data.features),group,category:categories.find(c=>c.id===group)!.name,images:await safeImages(data.images),priceCents:price,stock:existing?.stock||0,active:data.active===true,note:existing?.note||null,url:existing?.url||'',sourceDate:existing?.sourceDate||new Date().toISOString().slice(0,10),en:{name:string(enInput.name,2,180),subtitle:string(enInput.subtitle,10,1000),description:string(enInput.description,20,6000),details:lines(enInput.details),features:features(enInput.features),category:string(enInput.category,2,100)}};
if(existing){const saved=await db().prepare('UPDATE products SET data=?,price=?,stock=stock+?,active=?,updated_at=? WHERE id=? AND stock+? BETWEEN 0 AND 100000 RETURNING id').bind(JSON.stringify(p),price,delta,p.active?1:0,Date.now(),id,delta).first();assert(saved,409,'Stok değişti. Ekranı yenileyip tekrar dene.');}else await db().prepare('INSERT INTO products(id,data,price,stock,active,updated_at) VALUES(?,?,?,?,?,?)').bind(id,JSON.stringify(p),price,delta,p.active?1:0,Date.now()).run();await audit(actor,existing?'product.full_update':'product.create',id+'; inventoryDelta='+delta);return json({ok:true,id});}
export async function adminExtensions(req:Request,path:string,actor:string):Promise<Response|null>{const url=new URL(req.url);
if(path==='admin/analytics'&&req.method==='GET'){const days=int(Number(url.searchParams.get('days')||30),1,366),now=Date.now(),start=Math.floor((now+10800000)/86400000)*86400000-10800000-(days-1)*86400000;const[totals,daily,top,customers,counts,inventory]=await Promise.all([
db().prepare(salesCte+`SELECT COUNT(*) AS orders,COALESCE(SUM(CASE WHEN status IN (${paidStates}) THEN total ELSE 0 END),0) AS gross,COALESCE(SUM(CASE WHEN status IN (${paidStates}) THEN refunded_amount ELSE 0 END),0) AS refunded,SUM(CASE WHEN status IN (${paidStates}) THEN 1 ELSE 0 END) AS paidOrders FROM sales WHERE created_at>=?`).bind(start).first(),
db().prepare(salesCte+`SELECT strftime('%Y-%m-%d',created_at/1000,'unixepoch','+3 hours') AS day,COALESCE(SUM(CASE WHEN status IN (${paidStates}) THEN total-refunded_amount ELSE 0 END),0) AS revenue,COUNT(*) AS orders FROM sales WHERE created_at>=? GROUP BY day ORDER BY day`).bind(start).all(),
db().prepare(`SELECT l.product_id,l.name,SUM(l.quantity) AS units,SUM(l.quantity*l.price) AS revenue FROM order_lines l JOIN orders o ON o.id=l.order_id WHERE o.created_at>=? AND o.status IN ('paid','shipped','delivered') GROUP BY l.product_id ORDER BY revenue DESC LIMIT 6`).bind(start).all(),
db().prepare(`SELECT COUNT(DISTINCT lower(json_extract(customer,'$.email'))) AS n FROM orders WHERE created_at>=? AND status IN (${paidStates})`).bind(start).first(),
db().prepare('SELECT status,COUNT(*) AS n FROM orders GROUP BY status').all(),db().prepare('SELECT COUNT(*) AS products,SUM(stock) AS units,SUM(CASE WHEN active=1 AND stock=0 THEN 1 ELSE 0 END) AS outOfStock FROM products').first()]);return json({days,startDate:new Date(start+10800000).toISOString().slice(0,10),totals,daily:daily.results,top:top.results,customers:(customers as any)?.n||0,statuses:counts.results,inventory});}
if(path==='admin/customers'&&req.method==='GET'){
 const q=(url.searchParams.get('q')||'').slice(0,100),page=int(Number(url.searchParams.get('page')||1),1,10000);
 const cte=salesCte+`,summary AS (SELECT lower(json_extract(customer,'$.email')) AS email,json_extract(customer,'$.name') AS name,json_extract(customer,'$.surname') AS surname,json_extract(customer,'$.city') AS city,COUNT(*) AS orders,COALESCE(SUM(CASE WHEN status IN (${paidStates}) THEN total-refunded_amount ELSE 0 END),0) AS spent,MAX(created_at) AS lastOrder FROM sales GROUP BY email),directory AS (SELECT COALESCE(s.email,c.email) AS email,COALESCE(c.name,s.name) AS name,CASE WHEN c.id IS NULL THEN s.surname ELSE '' END AS surname,COALESCE(s.city,'') AS city,COALESCE(s.orders,0) AS orders,COALESCE(s.spent,0) AS spent,s.lastOrder,c.created_at AS registeredAt FROM customers c LEFT JOIN summary s ON s.email=c.email UNION ALL SELECT s.*,NULL AS registeredAt FROM summary s WHERE NOT EXISTS(SELECT 1 FROM customers c WHERE c.email=s.email)) `;
 const where="WHERE email LIKE ? OR name LIKE ? OR surname LIKE ?",values=Array(3).fill('%'+q+'%');
 const[rows,count]=await Promise.all([db().prepare(cte+'SELECT * FROM directory '+where+' ORDER BY COALESCE(lastOrder,registeredAt) DESC LIMIT 30 OFFSET ?').bind(...values,(page-1)*30).all(),db().prepare(cte+'SELECT COUNT(*) AS n FROM directory '+where).bind(...values).first<{n:number}>()]);return json({customers:rows.results,total:count?.n||0,page,pages:Math.max(1,Math.ceil((count?.n||0)/30))});
}
if(path==='admin/products/save'&&req.method==='POST')return saveProduct(await body(req),actor);
if(path==='admin/inventory'&&req.method==='POST'){const data=await body(req);assert(Array.isArray(data.changes)&&data.changes.length>0&&data.changes.length<=100,400,'Stok değişikliklerini kontrol et.');const seen=new Set<string>(),changes:Array<{id:string;delta:number}>=data.changes.map((v:any)=>{const id=string(v.id,1,30),delta=int(v.delta,-100000,100000);assert(!seen.has(id),400,'Aynı ürün iki kez güncellenemez.');seen.add(id);return{id,delta}});const products=await getProducts();for(const c of changes)assert(products.some(p=>p.id===c.id),404,'Ürün bulunamadı.');const results=await db().batch(changes.map(c=>db().prepare('UPDATE products SET stock=stock+?,updated_at=? WHERE id=? AND stock+? BETWEEN 0 AND 100000 RETURNING id,stock').bind(c.delta,Date.now(),c.id,c.delta)));const applied=results.flatMap(r=>r.results as any[]).map(r=>r.id);await audit(actor,'inventory.adjust',JSON.stringify(changes.filter(c=>applied.includes(c.id))));return json({ok:true,applied,skipped:changes.filter(c=>!applied.includes(c.id)).map(c=>c.id)});}
if(path==='admin/exchange'&&req.method==='POST'){const rate=await fetchOfficialRate(),settings=await getSettings();assert(rate.rateDate>=settings.exchange.rateDate,409,'Daha eski kurla mevcut değer değiştirilemez.');await db().prepare("INSERT INTO settings(key,value) VALUES('store',?) ON CONFLICT(key) DO UPDATE SET value=json_patch(settings.value,excluded.value)").bind(JSON.stringify({exchange:rate})).run();await audit(actor,'exchange.refresh',rate.rateDate+'; '+rate.tryPerUsd);return json({ok:true,exchange:rate});}
if(path==='admin/merchandising'&&req.method==='POST'){const data=await body(req),settings=await getSettings(),products=await getProducts(),heroIds=lines(data.heroIds,5),featuredIds=lines(data.featuredIds,12);assert(heroIds.length&&featuredIds.length,400,'Vitrin ve öne çıkan ürünler boş olamaz.');for(const ids of [heroIds,featuredIds]){assert(new Set(ids).size===ids.length,400,'Bir ürünü bir kez seç.');assert(ids.every(id=>products.some(p=>p.id===id&&p.active)),400,'Vitrinde yalnızca görünür ürünler kullanılabilir.');}const merchandising={heroIds,featuredIds,announcementTr:string(data.announcementTr,5,160),announcementEn:string(data.announcementEn,5,160)};await db().prepare("INSERT INTO settings(key,value) VALUES('store',?) ON CONFLICT(key) DO UPDATE SET value=json_patch(settings.value,excluded.value)").bind(JSON.stringify({merchandising})).run();await audit(actor,'storefront.update','hero; featured; announcement');return json({ok:true});}
if(path==='admin/media'&&req.method==='GET'){assert(env.MEDIA,503,'Medya depolaması henüz bağlanmadı.');const cursor=url.searchParams.get('cursor')||undefined;assert(!cursor||cursor.length<=4096,400,'Geçersiz medya sayfası.');const result=await env.MEDIA.list({prefix:'products/',limit:100,cursor});return json({media:result.objects.map(o=>({key:o.key,url:'/api/media/'+o.key.slice(9),size:o.size,uploaded:o.uploaded})),truncated:result.truncated,cursor:result.truncated?result.cursor:null});}
if(path==='admin/media/upload'&&req.method==='POST'){assert(env.MEDIA,503,'Medya depolaması henüz bağlanmadı.');const type=req.headers.get('content-type'),bytes=new Uint8Array(await req.arrayBuffer());assert(bytes.length>16&&bytes.length<=4*1024*1024,413,'Görsel en fazla 4 MB olabilir.');const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71,jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255,webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';assert((type==='image/jpeg'&&jpg)||(type==='image/png'&&png)||(type==='image/webp'&&webp),415,'Yalnızca geçerli JPG, PNG veya WebP görselleri yüklenebilir.');const filename=crypto.randomUUID()+'.'+(png?'png':jpg?'jpg':'webp');await env.MEDIA.put('products/'+filename,bytes,{httpMetadata:{contentType:type!,cacheControl:'public, max-age=31536000, immutable'}});await audit(actor,'media.upload',filename);return json({ok:true,url:'/api/media/'+filename});}
return null;}
export async function publicMedia(path:string){const filename=path.slice('media/'.length);assert(/^[a-f0-9-]+\.(jpg|png|webp)$/.test(filename),404,'Görsel bulunamadı.');assert(env.MEDIA,404,'Görsel bulunamadı.');const object=await env.MEDIA.get('products/'+filename);assert(object,404,'Görsel bulunamadı.');return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}});}
