import {clientIp} from './client-ip';
import {db,getProducts,getSettings,publicConfig,runtime,type Session} from './server';
import {assert,email,string,int,HttpError,toCents} from './security';
import {iyzico,verifyResponse,checkoutUrl} from './iyzico';
import type {Cart,StoreSettings} from './catalog';
import {drainMail} from './mail';
export type Order={id:string;number:string;session:string;status:string;customer:string;subtotal:number;shipping:number;total:number;token:string|null;payment_url:string|null;payment_id:string|null;payment_data:string|null;expires:number|null;tracking:string|null;carrier:string|null;consent:string;created_at:number;updated_at:number};
export const activeOrderStates=['initializing','pending','review','reconcile'];
export async function getCart(s:Session):Promise<Cart>{const [products,settings,rows]=await Promise.all([getProducts(),getSettings(),db().prepare('SELECT product_id,quantity FROM cart_items WHERE session=?').bind(s.id).all<{product_id:string;quantity:number}>()]);const items=rows.results.flatMap(r=>{const p=products.find(p=>p.id===r.product_id);return p?[{product:p,quantity:r.quantity}]:[]});const subtotal=items.reduce((n,l)=>n+l.product.priceCents*l.quantity,0);const shipping=subtotal>0&&settings.shippingConfigured&&!(settings.freeShippingCents>0&&subtotal>=settings.freeShippingCents)?settings.shippingCents:0;return{items,subtotal,shipping,total:subtotal+shipping,count:items.reduce((n,l)=>n+l.quantity,0),csrf:s.csrf};}
export async function setCart(s:Session,data:Record<string,unknown>){const id=string(data.productId,1,30),qty=int(data.quantity,0,20);if(qty===0){await db().prepare('DELETE FROM cart_items WHERE session=? AND product_id=?').bind(s.id,id).run();}else{const product=(await getProducts()).find(p=>p.id===id);assert(product&&product.active,404,'Ürün bulunamadı.');await db().prepare('INSERT INTO cart_items(session,product_id,quantity) VALUES(?,?,?) ON CONFLICT(session,product_id) DO UPDATE SET quantity=excluded.quantity').bind(s.id,id,qty).run();}return getCart(s);}
function customerInput(data:Record<string,unknown>){const c={name:string(data.name,2,70),surname:string(data.surname,2,70),email:email(data.email),phone:string(data.phone,10,20),city:string(data.city,2,50),district:string(data.district,2,80),address:string(data.address,15,500),postalCode:string(data.postalCode,5,5),note:string(data.note??'',0,500)};assert(/^\+?[\d\s()-]{10,20}$/.test(c.phone),400,'Telefon numaranı kontrol et.');assert(/^\d{5}$/.test(c.postalCode),400,'Posta kodu 5 rakam olmalı.');const identity=string(data.identityNumber,11,11);assert(/^\d{11}$/.test(identity),400,'Kimlik numarası 11 rakam olmalı.');assert(data.terms===true,400,'Ön bilgilendirme ve mesafeli satış sözleşmesini onaylamalısın.');return {customer:c,identity};}
export function legalSnapshot(settings:StoreSettings,cart:Cart){return{version:'2026-09-06',acceptedAt:new Date().toISOString(),seller:settings.business,items:cart.items.map(l=>({id:l.product.id,name:l.product.name,features:l.product.features,quantity:l.quantity,unitPrice:l.product.priceCents})),subtotal:cart.subtotal,shipping:cart.shipping,total:cart.total,currency:'TRY',dispatchDays:settings.dispatchDays,withdrawalDays:14,terms:'Teslimden itibaren 14 gün cayma hakkı; bildirimi izleyen 14 günde geri gönderim. Belirtilen taşıyıcıya teslimden (başka taşıyıcı kullanıldığında satıcıya ulaştığı tarihten) itibaren 14 günde aynı ödeme aracına geri ödeme. Belirtilen iade taşıyıcısıyla iade masrafı tüketiciye yüklenmez. Ayıplı mala ilişkin kanuni haklar saklıdır. Taahhüt edilen teslim süresi saklı olmak üzere standart ürünler en geç 30 gün içinde teslim edilir. Kişiye özel hazırlanan ve kanuni istisna kapsamındaki mallar ayrıca değerlendirilir.'};}
export async function checkout(req:Request,s:Session,data:Record<string,unknown>){const cfg=await publicConfig();assert(cfg.orderingReady,503,'Mağazamız şu anda sipariş kabul etmiyor. Ürünleri keşfedebilir ve stok haberi talep edebilirsin.');const {customer,identity}=customerInput(data);const existing=await db().prepare("SELECT * FROM orders WHERE session=? AND status IN ('initializing','pending','review','reconcile') ORDER BY created_at DESC LIMIT 1").bind(s.id).first<Order>();if(existing){throw new HttpError(409,'Devam eden bir siparişin var. Siparişlerim sayfasından kayıtlı ürünleri ve adresi kontrol ederek o siparişin ödemesini sürdürebilirsin.');}
const cart=await getCart(s);assert(data.expectedTotal===cart.total,409,'Sepet tutarı değişti. Sayfayı yenileyerek güncel toplamı kontrol et.');assert(cart.items.length>0&&cart.items.length<=20,400,'Sepetine bir ürün ekle.');assert(cart.total>0&&cart.total<=100000000,400,'Sipariş tutarı geçersiz.');for(const l of cart.items)assert(l.product.active&&l.product.stock>=l.quantity,409,'Sepetindeki bir ürünün stoku değişti. Sepetini güncelle.');const id=crypto.randomUUID(),number='SC-'+new Date().getFullYear()+'-'+crypto.randomUUID().replaceAll('-','').slice(0,10).toUpperCase(),now=Date.now();
try{await db().batch([db().prepare('INSERT INTO orders (id,number,session,status,customer,subtotal,shipping,total,consent,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,number,s.id,'initializing',JSON.stringify(customer),cart.subtotal,cart.shipping,cart.total,JSON.stringify(legalSnapshot(cfg,cart)),now,now),...cart.items.map(l=>db().prepare('INSERT INTO order_lines(order_id,product_id,name,quantity,price) VALUES(?,?,?,?,?)').bind(id,l.product.id,l.product.name,l.quantity,l.product.priceCents))]);}catch{throw new HttpError(409,'Stok veya sipariş durumu değişti. Sepetini yenileyip tekrar dene.');}
const origin=String(runtime().APP_ORIGIN);const contactName=customer.name+' '+customer.surname,address=customer.address+' '+customer.district;const requestPayload={locale:data.locale==='en'?'en':'tr',conversationId:id,basketId:id,price:(cart.total/100).toFixed(2),paidPrice:(cart.total/100).toFixed(2),currency:'TRY',paymentGroup:'PRODUCT',callbackUrl:origin+'/api/payments/callback',enabledInstallments:[1],buyer:{id:s.id,name:customer.name,surname:customer.surname,identityNumber:identity,email:customer.email,gsmNumber:customer.phone,registrationAddress:address,city:customer.city,country:'Turkey',zipCode:customer.postalCode,ip:clientIp(req)},shippingAddress:{contactName,address,city:customer.city,country:'Turkey',zipCode:customer.postalCode},billingAddress:{contactName,address,city:customer.city,country:'Turkey',zipCode:customer.postalCode},basketItems:[...cart.items.map(l=>({id:l.product.id,name:l.product.name,category1:l.product.category,itemType:'PHYSICAL',price:(l.product.priceCents*l.quantity/100).toFixed(2)})),...(cart.shipping?[{id:'shipping',name:'Kargo',category1:'Kargo',itemType:'VIRTUAL',price:(cart.shipping/100).toFixed(2)}]:[])]};
try{const result=await iyzico('/payment/iyzipos/checkoutform/initialize/auth/ecom',requestPayload);if(result.status!=='success'){await db().prepare("UPDATE orders SET status='failed',updated_at=? WHERE id=? AND status='initializing'").bind(Date.now(),id).run();throw new HttpError(502,'Ödeme başlatılamadı. Bilgilerini kontrol ederek tekrar dene.');}await verifyResponse(result,'init');assert(result.conversationId===id&&typeof result.token==='string',502,'Ödeme kaydı eşleştirilemedi.');const url=checkoutUrl(result.paymentPageUrl),expires=Date.now()+Math.min(Number(result.tokenExpireTime)||1800,3600)*1000;await db().prepare("UPDATE orders SET token=?,payment_url=?,expires=?,status='pending',updated_at=? WHERE id=? AND status='initializing'").bind(result.token,url,expires,Date.now(),id).run();return{url,order:number};}catch(error){await db().prepare("UPDATE orders SET status='reconcile',updated_at=? WHERE id=? AND status='initializing'").bind(Date.now(),id).run();throw error;}}
async function reconcileProvider(order:Order){assert(order.token,409,'Ödeme sağlayıcısındaki sonuç yönetimden kontrol edilmeli.');if(['paid','shipped','delivered','refunded'].includes(order.status))return order;const result=await iyzico('/payment/iyzipos/checkoutform/auth/ecom/detail',{locale:'tr',conversationId:order.id,token:order.token});assert(result.status==='success',502,'Ödeme sonucu henüz doğrulanamadı.');await verifyResponse(result,'detail');assert(result.token===order.token&&result.basketId===order.id&&result.conversationId===order.id&&result.currency==='TRY'&&toCents(result.price)===order.total&&toCents(result.paidPrice)===order.total,502,'Ödeme sonucu siparişle eşleşmiyor.');let status='pending';if(result.paymentStatus==='SUCCESS'){assert([1,0,-1].includes(Number(result.fraudStatus)),502,'Ödeme inceleme durumu doğrulanamadı.');status=Number(result.fraudStatus)===1?'paid':Number(result.fraudStatus)===0?'review':'rejected';}else if(result.paymentStatus==='FAILURE')status='failed';else assert(result.paymentStatus==='INIT_THREEDS'||result.paymentStatus==='CALLBACK_THREEDS',502,'Ödeme durumu henüz kesinleşmedi.');const paymentData=JSON.stringify({fraudStatus:result.fraudStatus,itemTransactions:result.itemTransactions,paymentStatus:result.paymentStatus});await db().prepare("UPDATE orders SET status=?,payment_id=?,payment_data=?,updated_at=? WHERE id=? AND status IN ('initializing','pending','review','reconcile')").bind(status,result.paymentId?String(result.paymentId):null,paymentData,Date.now(),order.id).run();return await db().prepare('SELECT * FROM orders WHERE id=?').bind(order.id).first<Order>();}
export async function orderView(order:Order){const lines=await db().prepare('SELECT product_id,name,quantity,price FROM order_lines WHERE order_id=?').bind(order.id).all();return{number:order.number,status:order.status,total:order.total,subtotal:order.subtotal,shipping:order.shipping,createdAt:order.created_at,tracking:order.tracking,carrier:order.carrier,items:lines.results,customer:JSON.parse(order.customer),contract:JSON.parse(order.consent)};}
export async function reconcile(order:Order){const key='reconcile:'+order.id,now=Date.now();const lock=await db().prepare('INSERT INTO rate_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET expires=excluded.expires WHERE rate_limits.expires<? RETURNING key').bind(key,now+30000,now).first();assert(lock,409,'Ödeme kontrolü sürüyor. Birkaç saniye sonra tekrar dene.');try{const result=await reconcileProvider(order);await drainMail(order.id);return result;}finally{await db().prepare('UPDATE rate_limits SET expires=? WHERE key=?').bind(Date.now()+5000,key).run();}}
