import {runtime} from './server';
import {assert,hmac,timingEqual,normalizedMoney,HttpError} from './security';
export type IyziResponse=Record<string,any>;
// This authenticated metadata query never creates a payment or uses a customer's card.
export async function checkIyzicoCredentials(){
  const conversationId='sc-connection-'+crypto.randomUUID();
  const result=await iyzico('/payment/bin/check',{locale:'tr',binNumber:'41579200',conversationId});
  const code=/^\d{1,8}$/.test(String(result.errorCode))?String(result.errorCode):undefined;
  assert(result.status==='success'&&result.conversationId===conversationId&&result.binNumber==='41579200',502,'iyzico bağlantısı doğrulanamadı.'+(code?' Sağlayıcı hata kodu: '+code:'')+' Canlı/test ortamını ve iki anahtarı kontrol et.');
  return{ok:true,mode:runtime().IYZICO_MODE,checkedAt:Date.now(),charged:false};
}
export async function iyzico(path:string,payload:Record<string,unknown>):Promise<IyziResponse>{const e=runtime();assert(e.IYZICO_API_KEY&&e.IYZICO_SECRET_KEY,503,'Ödeme hizmeti henüz etkin değil.');assert(e.IYZICO_MODE==='live'||e.IYZICO_MODE==='sandbox',503,'iyzico ortamı live veya sandbox olmalı.');const base=e.IYZICO_MODE==='live'?'https://api.iyzipay.com':'https://sandbox-api.iyzipay.com';const body=JSON.stringify(payload);const randomKey=Date.now()+crypto.randomUUID();const signature=await hmac(String(e.IYZICO_SECRET_KEY),randomKey+path+body);const response=await fetch(base+path,{method:'POST',redirect:'error',headers:{'Content-Type':'application/json','Authorization':'IYZWSv2 '+btoa(`apiKey:${e.IYZICO_API_KEY}&randomKey:${randomKey}&signature:${signature}`),'x-iyzi-rnd':randomKey},body,signal:AbortSignal.timeout(18000)});assert(response.ok,502,'Ödeme sağlayıcısı ile bağlantı doğrulanamadı.');return await response.json() as IyziResponse;}
export async function verifyResponse(data:IyziResponse,kind:'init'|'detail'|'refund'){const fields=kind==='init'?['conversationId','token']:kind==='refund'?['paymentId','price','currency','conversationId']:['paymentStatus','paymentId','currency','basketId','conversationId','paidPrice','price','token'];const values=fields.map(k=>k==='price'||k==='paidPrice'?normalizedMoney(data[k]):String(data[k]??''));const expected=await hmac(String(runtime().IYZICO_SECRET_KEY),values.join(':'));assert(typeof data.signature==='string'&&timingEqual(expected,data.signature.toLowerCase()),502,'Ödeme yanıtının güvenliği doğrulanamadı.');}
export function checkoutUrl(value:unknown){assert(typeof value==='string',502,'Ödeme bağlantısı alınamadı.');const url=new URL(value);assert(url.protocol==='https:'&&!url.username&&!url.password&&!url.port&&(url.hostname==='iyzico.com'||url.hostname.endsWith('.iyzico.com')||url.hostname==='iyzipay.com'||url.hostname.endsWith('.iyzipay.com')),502,'Ödeme adresi doğrulanamadı.');return url.href;}
export async function verifyWebhook(req:Request,data:IyziResponse){const secret=String(runtime().IYZICO_SECRET_KEY||'');assert(secret,503,'Ödeme yapılandırması eksik.');const message=secret+String(data.iyziEventType??'')+String(data.iyziPaymentId??'')+String(data.token??'')+String(data.paymentConversationId??'')+String(data.status??'');const hash=await hmac(secret,message);assert(timingEqual(hash,(req.headers.get('x-iyz-signature-v3')||'').toLowerCase()),403,'Geçersiz bildirim imzası.');}
