import {env} from 'cloudflare:workers';
import {initialProducts,defaultSettings,type Product,type StoreSettings,type PublicConfig} from './catalog';
import {assert,randomToken,sha,timingEqual,HttpError} from './security';
export const runtime=()=>env as unknown as Record<string,string|D1Database|undefined>;
export function db(){const value=env.DB;assert(value,503,'Mağaza kısa süre içinde yeniden hazır olacak.');return value;}
export async function getProducts():Promise<Product[]>{const database=db();let rows=await database.prepare('SELECT * FROM products').all<{id:string;data:string;price:number;stock:number;active:number}>();if(rows.results.length<initialProducts.length){await database.batch(initialProducts.map(p=>database.prepare('INSERT INTO products (id,data,price,stock,active,updated_at) VALUES (?,?,?,0,1,?) ON CONFLICT(id) DO NOTHING').bind(p.id,JSON.stringify(p),p.priceCents,Date.now())));rows=await database.prepare('SELECT * FROM products').all();}return rows.results.map(r=>({...JSON.parse(r.data),priceCents:r.price,stock:r.stock,active:!!r.active})).sort((a,b)=>initialProducts.findIndex(p=>p.id===a.id)-initialProducts.findIndex(p=>p.id===b.id));}
export async function getSettings():Promise<StoreSettings>{const row=await db().prepare('SELECT value FROM settings WHERE key=?').bind('store').first<{value:string}>();return row?{...defaultSettings,...JSON.parse(row.value)}:defaultSettings;}
export function paymentReady(){const e=runtime();return !!(e.IYZICO_API_KEY&&e.IYZICO_SECRET_KEY&&e.IYZICO_MODE==='live'&&e.APP_ORIGIN&&e.IYZICO_VERIFIED==='true'&&e.RESEND_API_KEY&&e.EMAIL_FROM&&e.ADMIN_BOOTSTRAP_PRIVATE!=='true');}
export function legalReady(s:StoreSettings){return s.legalReviewed&&s.shippingConfigured&&Object.entries(s.business).filter(([key])=>!['mersis','chamber'].includes(key)).every(([,value])=>!!value.trim());}
export async function publicConfig():Promise<PublicConfig>{const s=await getSettings();return {...s,paymentReady:paymentReady(),orderingReady:paymentReady()&&legalReady(s)&&s.checkoutEnabled};}
export type Session={id:string;csrf:string;cookie?:string};
export async function session(req:Request,create=true):Promise<Session>{const raw=req.headers.get('cookie')?.match(/(?:^|;\s*)sc_session=([a-f0-9]{64})(?:;|$)/)?.[1];if(raw){const id=await sha(raw);const row=await db().prepare('SELECT id,csrf FROM sessions WHERE id=? AND expires>?').bind(id,Date.now()).first<Session>();if(row)return row;}
assert(create,401,'Oturumun sona erdi. Sayfayı yenileyip tekrar dene.');const token=randomToken(),id=await sha(token),csrf=randomToken();await db().prepare('INSERT INTO sessions(id,csrf,expires) VALUES(?,?,?)').bind(id,csrf,Date.now()+30*86400000).run();const secure=new URL(req.url).protocol==='https:'?'; Secure':'';return{id,csrf,cookie:`sc_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=2592000${secure}`};}
export async function requireMutation(req:Request,s:Session){const origin=req.headers.get('origin'),url=new URL(req.url);assert(origin===url.origin&&req.headers.get('sec-fetch-site')!=='cross-site',403,'Bu isteğin kaynağı doğrulanamadı.');assert(timingEqual(req.headers.get('x-csrf-token')||'',s.csrf),403,'Oturumunu yenileyip tekrar dene.');}
export async function body(req:Request){assert(req.headers.get('content-type')?.includes('application/json'),415,'İstek biçimi desteklenmiyor.');assert(Number(req.headers.get('content-length')||0)<=16000,413,'İstek çok büyük.');const raw=await req.text();assert(raw.length<=16000,413,'İstek çok büyük.');try{const value=JSON.parse(raw);assert(value&&typeof value==='object'&&!Array.isArray(value),400,'Geçersiz istek.');return value;}catch(error){if(error instanceof HttpError)throw error;throw new HttpError(400,'İstek okunamadı.');}}
export async function rateLimit(req:Request,bucket:string,max=40){const ip=req.headers.get('cf-connecting-ip')||'local';const now=Date.now();const key=await sha(`${bucket}:${ip}:${Math.floor(now/600000)}`);const row=await db().prepare('INSERT INTO rate_limits(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+1200000).first<{count:number}>();assert(row&&row.count<=max,429,'Biraz hızlı gidiyoruz. Birkaç dakika sonra tekrar dene.');}
export async function requireAdmin(req:Request){const id=req.headers.get('oai-authenticated-user-id'),mail=req.headers.get('oai-authenticated-user-email');assert(id&&mail,401,'Yönetim için güvenli giriş yapmalısın.');const allow=String(runtime().ADMIN_EMAILS||'').toLowerCase().split(',').map(v=>v.trim()).filter(Boolean);if(allow.includes(mail.toLowerCase()))return id;
let row=await db().prepare("SELECT value FROM settings WHERE key='admin_owner'").first<{value:string}>();if(!row&&runtime().ADMIN_BOOTSTRAP_PRIVATE==='true'){// Enabled only while the Sites dispatcher is OWNER_ONLY. Disable before public access.
await db().prepare("INSERT INTO settings(key,value) VALUES('admin_owner',?) ON CONFLICT(key) DO NOTHING").bind(id).run();row=await db().prepare("SELECT value FROM settings WHERE key='admin_owner'").first<{value:string}>();}
assert(row?.value===id,403,'Bu hesabın mağaza yönetimine erişimi yok.');return id;}
export async function audit(actor:string,action:string,target:string){await db().prepare('INSERT INTO audit_log(id,actor,action,target,created_at) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),actor,action,target,Date.now()).run();}
export function json(data:unknown,status=200,cookie?:string){return Response.json(data,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...(cookie?{'Set-Cookie':cookie}:{})}});}
export async function boundedRequest(req:Request,max=16000){assert(Number(req.headers.get('content-length')||0)<=max,413,'İstek çok büyük.');if(!req.body)return req;const reader=req.body.getReader(),chunks:Uint8Array[]=[];let size=0;while(true){const{value,done}=await reader.read();if(done)break;size+=value.byteLength;if(size>max){await reader.cancel();throw new HttpError(413,'İstek çok büyük.');}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength;}return new Request(req.url,{method:req.method,headers:req.headers,body:bytes,redirect:req.redirect});}
