import {sqliteTable,text,integer,index,uniqueIndex,primaryKey} from 'drizzle-orm/sqlite-core';
export const products=sqliteTable('products',{id:text('id').primaryKey(),data:text('data').notNull(),price:integer('price').notNull(),stock:integer('stock').notNull().default(0),active:integer('active').notNull().default(1),updatedAt:integer('updated_at').notNull()});
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),csrf:text('csrf').notNull(),expires:integer('expires').notNull()},t=>[index('idx_sessions_expires').on(t.expires)]);
export const cartItems=sqliteTable('cart_items',{session:text('session').notNull(),productId:text('product_id').notNull(),quantity:integer('quantity').notNull()},t=>[primaryKey({columns:[t.session,t.productId]})]);
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),number:text('number').notNull(),session:text('session').notNull(),customerId:text('customer_id'),status:text('status').notNull(),customer:text('customer').notNull(),subtotal:integer('subtotal').notNull(),shipping:integer('shipping').notNull(),total:integer('total').notNull(),token:text('token'),paymentUrl:text('payment_url'),paymentId:text('payment_id'),paymentData:text('payment_data'),expires:integer('expires'),tracking:text('tracking'),carrier:text('carrier'),consent:text('consent').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('idx_orders_number').on(t.number),uniqueIndex('idx_orders_token').on(t.token),index('idx_orders_session_created').on(t.session,t.createdAt),index('idx_orders_status_created').on(t.status,t.createdAt)]);
export const orderLines=sqliteTable('order_lines',{orderId:text('order_id').notNull(),productId:text('product_id').notNull(),name:text('name').notNull(),quantity:integer('quantity').notNull(),price:integer('price').notNull()},t=>[primaryKey({columns:[t.orderId,t.productId]})]);
export const requests=sqliteTable('requests',{id:text('id').primaryKey(),kind:text('kind').notNull(),email:text('email').notNull(),productId:text('product_id'),body:text('body').notNull(),status:text('status').notNull().default('new'),createdAt:integer('created_at').notNull()},t=>[index('idx_requests_kind_status').on(t.kind,t.status)]);
export const limits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const audit=sqliteTable('audit_log',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),createdAt:integer('created_at').notNull()},t=>[index('idx_audit_created').on(t.createdAt)]);
export const refunds=sqliteTable('refund_actions',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),transactionId:text('transaction_id').notNull(),amount:integer('amount').notNull(),status:text('status').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull()},t=>[uniqueIndex('idx_refund_transaction').on(t.transactionId),index('idx_refund_order').on(t.orderId)]);
export const outbox=sqliteTable('mail_outbox',{id:text('id').primaryKey(),orderId:text('order_id').notNull(),kind:text('kind').notNull(),status:text('status').notNull(),payload:text('payload'),providerId:text('provider_id'),firstAttempt:integer('first_attempt'),updatedAt:integer('updated_at').notNull()},t=>[index('idx_outbox_status_updated').on(t.status,t.updatedAt)]);

export const notifications=sqliteTable('notification_outbox',{id:text('id').primaryKey(),sourceId:text('source_id').notNull(),kind:text('kind').notNull(),status:text('status').notNull().default('ready'),payload:text('payload'),providerId:text('provider_id'),firstAttempt:integer('first_attempt'),updatedAt:integer('updated_at').notNull()},t=>[index('idx_notifications_status_updated').on(t.status,t.updatedAt)]);

export const customers=sqliteTable('customers',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),digest:text('digest').notNull(),version:text('version').notNull(),createdAt:integer('created_at').notNull(),privacyVersion:text('privacy_version').notNull()},t=>[uniqueIndex('idx_customers_email').on(t.email)]);
export const customerSessions=sqliteTable('customer_sessions',{id:text('id').primaryKey(),customerId:text('customer_id').notNull(),version:text('version').notNull(),browserSession:text('browser_session').notNull(),expires:integer('expires').notNull(),lastSeen:integer('last_seen').notNull()},t=>[index('idx_customer_sessions_customer').on(t.customerId),index('idx_customer_sessions_expires').on(t.expires)]);
export const customerResetTokens=sqliteTable('customer_reset_tokens',{id:text('id').primaryKey(),customerId:text('customer_id').notNull(),version:text('version').notNull(),expires:integer('expires').notNull()},t=>[index('idx_customer_reset_customer').on(t.customerId)]);
